---
common: &common
  agents:
    - "capable_of_building=online-services"
    - "environment=${CI_ENVIRONMENT:-production}"
    - "machine_type=single"
    - "node_stability=interruptible"
    - "permission_set=builder"
    - "platform=linux"
    - "queue=${CI_BUILDER_QUEUE:-v4-2020-01-15-bk6453-e9769eaa1b1caa58}"
    - "scaler_version=2"
  timeout_in_minutes: 5
  retry:
    automatic:
        # This is designed to trap and retry failures because agent lost connection. Agent exits with -1 in this case.
      - exit_status: -1
        limit: 3
      - exit_status: 255
        limit: 3

# NOTE: step labels turn into commit-status names like {org}/{repo}/{pipeline}/{step-label}, lower-case and hyphenated.
# These are then relied on to have stable names by other things, so once named, please beware renaming has consequences.

dag: true

steps:
  - label: "build :bash:"
    id: "build"
    command: "ci/build.sh"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    timeout_in_minutes: 15

  - label: "unit tests"
    id: "unit-test"
    command: "ci/unit-tests.sh"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    timeout_in_minutes: 15
    artifact_paths:
      - "*.xml"
    depends_on:
      - step: "build"

  - label: "integration tests"
    id: "integration-test"
    command: "ci/integration-tests.sh"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    timeout_in_minutes: 15
    artifact_paths:
      - "*.xml"
    depends_on:
      - step: "build"

  - label: "dotnet format"
    id: "format"
    command: "ci/format.sh"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    timeout_in_minutes: 15

  - label: "analytics-endpoint"
    command: "ci/analytics-endpoint.sh"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    timeout_in_minutes: 15

  - label: "annotate test results :pencil2:"
    depends_on: 
      - step: "unit-test"
        allow_failure: true
      - step: "integration-test"
        allow_failure: true
    plugins:
      - improbable/test-summary#d7289cac8297018fd1b452dcf828979307b3ebc6:
          inputs:
            - label: ":octagonal_sign: Test failures "
              artifact_path: "*.xml"
              type: nunit
          formatter:
            type: details
    <<: *common
