---
common: &common
  agents:
    - "capable_of_building=online-services"
    - "environment=production"
    - "permission_set=builder"
    - "queue=${CI_BUILDER_QUEUE:-v3-1559657210-cbf47979a9aab331-------z}"
  timeout_in_minutes: 5
  retry:
    automatic:
        # This is designed to trap and retry failures because agent lost connection. Agent exits with -1 in this case.
      - exit_status: -1
        limit: 3

# NOTE: step labels turn into commit-status names like {org}/{repo}/{pipeline}/{step-label}, lower-case and hyphenated.
# These are then relied on to have stable names by other things, so once named, please beware renaming has consequences.

steps:
  - label: "build :bash:"
    command: "ci/build.sh"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    timeout_in_minutes: 15
  - label: "dotnet format"
    command: "ci/format.sh"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    timeout_in_minutes: 15
  - label: "analytics-pipeline :100:"
    command: "ci/analytics-pipeline.sh"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    timeout_in_minutes: 15
